CC = gcc
CFLAGS = -shared -fPIC -O2 -Wall -I ..

all: adder adder1 adder2 adder3 adder4 adder5 adder6 adder7 adder8 adder9 adder10 adder11 adder12 adder13 adder14 adder15 adder16 adder17 adder18 adder19 adder20

adder: adder.c csapp.o
	$(CC) $(CFLAGS) -o adder.so adder.c csapp.o

adder1: adder1.c csapp.o
	$(CC) $(CFLAGS) -o adder1.so adder1.c csapp.o

adder2: adder2.c csapp.o
	$(CC) $(CFLAGS) -o adder2.so adder2.c csapp.o

adder3: adder3.c csapp.o
	$(CC) $(CFLAGS) -o adder3.so adder3.c csapp.o

adder4: adder4.c csapp.o
	$(CC) $(CFLAGS) -o adder4.so adder4.c csapp.o

adder5: adder5.c csapp.o
	$(CC) $(CFLAGS) -o adder5.so adder5.c csapp.o

adder6: adder6.c csapp.o
	$(CC) $(CFLAGS) -o adder6.so adder6.c csapp.o

adder7: adder7.c csapp.o
	$(CC) $(CFLAGS) -o adder7.so adder7.c csapp.o

adder8: adder8.c csapp.o
	$(CC) $(CFLAGS) -o adder8.so adder8.c csapp.o

adder9: adder9.c csapp.o
	$(CC) $(CFLAGS) -o adder9.so adder9.c csapp.o

adder10: adder10.c csapp.o
	$(CC) $(CFLAGS) -o adder10.so adder10.c csapp.o

adder11: adder11.c csapp.o
	$(CC) $(CFLAGS) -o adder11.so adder11.c csapp.o

adder12: adder12.c csapp.o
	$(CC) $(CFLAGS) -o adder12.so adder12.c csapp.o

adder13: adder13.c csapp.o
	$(CC) $(CFLAGS) -o adder13.so adder13.c csapp.o

adder14: adder14.c csapp.o
	$(CC) $(CFLAGS) -o adder14.so adder14.c csapp.o

adder15: adder15.c csapp.o
	$(CC) $(CFLAGS) -o adder15.so adder15.c csapp.o

adder16: adder16.c csapp.o
	$(CC) $(CFLAGS) -o adder16.so adder16.c csapp.o

adder17: adder17.c csapp.o
	$(CC) $(CFLAGS) -o adder17.so adder17.c csapp.o

adder18: adder18.c csapp.o
	$(CC) $(CFLAGS) -o adder18.so adder18.c csapp.o

adder19: adder19.c csapp.o
	$(CC) $(CFLAGS) -o adder19.so adder19.c csapp.o

adder20: adder20.c csapp.o
	$(CC) $(CFLAGS) -o adder20.so adder20.c csapp.o

clean:
	rm -f *.o
