CC = gcc
CFLAGS = -O2 -Wall -I ..

all: adder adder1 adder2 adder3 adder4 adder5 adder6 adder7 adder8 adder9 adder10 adder11 adder12 adder13 adder14 adder15 adder16 adder17 adder18 adder19 adder20

adder: adder.c
	$(CC) $(CFLAGS) -o adder adder.c

adder1: adder1.c
	$(CC) $(CFLAGS) -o adder1 adder1.c

adder2: adder2.c
	$(CC) $(CFLAGS) -o adder2 adder2.c

adder3: adder3.c
	$(CC) $(CFLAGS) -o adder3 adder3.c

adder4: adder4.c
	$(CC) $(CFLAGS) -o adder4 adder4.c

adder5: adder5.c
	$(CC) $(CFLAGS) -o adder5 adder5.c

adder6: adder6.c
	$(CC) $(CFLAGS) -o adder6 adder6.c

adder7: adder7.c
	$(CC) $(CFLAGS) -o adder7 adder7.c

adder8: adder8.c
	$(CC) $(CFLAGS) -o adder8 adder8.c

adder9: adder9.c
	$(CC) $(CFLAGS) -o adder9 adder9.c

adder10: adder10.c
	$(CC) $(CFLAGS) -o adder10 adder10.c

adder11: adder11.c
	$(CC) $(CFLAGS) -o adder11 adder11.c

adder12: adder12.c
	$(CC) $(CFLAGS) -o adder12 adder12.c

adder13: adder13.c
	$(CC) $(CFLAGS) -o adder13 adder13.c

adder14: adder14.c
	$(CC) $(CFLAGS) -o adder14 adder14.c

adder15: adder15.c
	$(CC) $(CFLAGS) -o adder15 adder15.c

adder16: adder16.c
	$(CC) $(CFLAGS) -o adder16 adder16.c

adder17: adder17.c
	$(CC) $(CFLAGS) -o adder17 adder17.c

adder18: adder18.c
	$(CC) $(CFLAGS) -o adder18 adder18.c

adder19: adder19.c
	$(CC) $(CFLAGS) -o adder19 adder19.c

adder20: adder20.c
	$(CC) $(CFLAGS) -o adder20 adder20.c

clean:
	rm -f *.o
